import { createRouter, createWebHistory } from '@ionic/vue-router'
import type { RouteRecordRaw } from 'vue-router'
import HomePage from '../views/HomePage.vue'

const domainPage = () => import('../views/DomainPage.vue')

const routes: RouteRecordRaw[] = [
	{ path: '/', name: 'home', component: HomePage },
	{ path: '/home', redirect: '/' },
	{ path: '/search', name: 'search', component: () => import('../views/SearchPage.vue') },
	{
		path: '/profiles',
		name: 'profiles',
		component: domainPage,
		meta: { title: 'People', section: 'Profiles', description: 'Find a Tangled profile by handle or DID.' },
	},
	{
		path: '/profiles/:actor',
		name: 'profile',
		component: domainPage,
		meta: {
			title: 'Profile',
			section: 'People',
			description: 'Public identity, repositories, and relationships.',
			parameter: 'actor',
			identifierLabel: 'Actor',
			requirement: 'actor',
			back: '/profiles',
		},
	},
	{
		path: '/profiles/:actor/activity/:activity?',
		name: 'actor-activity',
		component: domainPage,
		meta: {
			title: 'Actor activity',
			section: 'People',
			description: 'Public records authored by this actor.',
			parameter: 'actor',
			identifierLabel: 'Actor',
			requirement: 'actor',
			back: '/profiles',
		},
	},
	{
		path: '/profiles/:actor/relationships/:relationship?',
		name: 'actor-relationships',
		component: domainPage,
		meta: {
			title: 'Relationships',
			section: 'People',
			description: 'Follows, followers, stars, and vouches for this actor.',
			parameter: 'actor',
			identifierLabel: 'Actor',
			requirement: 'actor',
			back: '/profiles',
		},
	},
	{
		path: '/repositories',
		name: 'repositories',
		component: domainPage,
		meta: {
			title: 'Repositories',
			section: 'Code',
			description: 'Open a public Tangled repository by its record AT-URI.',
		},
	},
	{
		path: '/repositories/:repo',
		name: 'repository',
		component: domainPage,
		meta: {
			title: 'Repository overview',
			section: 'Code',
			description: 'Repository identity, README, collaborators, labels, and activity.',
			parameter: 'repo',
			identifierLabel: 'Repository record',
			requirement: 'at-uri',
			back: '/repositories',
		},
	},
	{
		path: '/repositories/:repo/source',
		name: 'repository-source',
		component: domainPage,
		meta: {
			title: 'Source',
			section: 'Code',
			description: 'Browse a repository tree or blob at the ref and path in this URL.',
			parameter: 'repo',
			identifierLabel: 'Repository record',
			requirement: 'at-uri',
			back: '/repositories',
		},
	},
	{
		path: '/repositories/:repo/commits',
		name: 'repository-commits',
		component: domainPage,
		meta: {
			title: 'Commit history',
			section: 'Code',
			description: 'Browse repository history with optional ref and path filters.',
			parameter: 'repo',
			identifierLabel: 'Repository record',
			requirement: 'at-uri',
			back: '/repositories',
		},
	},
	{
		path: '/repositories/:repo/commits/:hash',
		name: 'repository-commit',
		component: domainPage,
		meta: {
			title: 'Commit',
			section: 'Code',
			description: 'Inspect one public Git commit.',
			parameter: 'repo',
			identifierLabel: 'Repository record',
			requirement: 'at-uri',
			back: '/repositories',
		},
	},
	{
		path: '/repositories/:repo/branches',
		name: 'repository-branches',
		component: domainPage,
		meta: {
			title: 'Branches',
			section: 'Code',
			description: 'Browse public repository branches.',
			parameter: 'repo',
			identifierLabel: 'Repository record',
			requirement: 'at-uri',
			back: '/repositories',
		},
	},
	{
		path: '/repositories/:repo/tags',
		name: 'repository-tags',
		component: domainPage,
		meta: {
			title: 'Tags',
			section: 'Code',
			description: 'Browse public repository tags.',
			parameter: 'repo',
			identifierLabel: 'Repository record',
			requirement: 'at-uri',
			back: '/repositories',
		},
	},
	{
		path: '/repositories/:repo/diff/:ref',
		name: 'repository-diff',
		component: domainPage,
		meta: {
			title: 'Diff',
			section: 'Code',
			description: 'Read the patch for one encoded revision.',
			parameter: 'repo',
			identifierLabel: 'Repository record',
			requirement: 'at-uri',
			back: '/repositories',
		},
	},
	{
		path: '/repositories/:repo/compare',
		name: 'repository-compare',
		component: domainPage,
		meta: {
			title: 'Compare revisions',
			section: 'Code',
			description: 'Compare the base and head revisions encoded in this URL.',
			parameter: 'repo',
			identifierLabel: 'Repository record',
			requirement: 'at-uri',
			back: '/repositories',
		},
	},
	{
		path: '/repositories/:repo/issues',
		name: 'issues',
		component: domainPage,
		meta: {
			title: 'Issues',
			section: 'Collaboration',
			description: 'Browse public issues and URL-preserved filters.',
			parameter: 'repo',
			identifierLabel: 'Repository record',
			requirement: 'at-uri',
			back: '/repositories',
		},
	},
	{
		path: '/repositories/:repo/issues/:rkey',
		name: 'issue',
		component: domainPage,
		meta: {
			title: 'Issue',
			section: 'Collaboration',
			description: 'Read an issue, its state history, labels, comments, and reactions.',
			parameter: 'repo',
			identifierLabel: 'Repository record',
			requirement: 'at-uri',
			back: '/repositories',
		},
	},
	{
		path: '/repositories/:repo/pulls',
		name: 'pulls',
		component: domainPage,
		meta: {
			title: 'Pull requests',
			section: 'Collaboration',
			description: 'Browse public pull requests and URL-preserved filters.',
			parameter: 'repo',
			identifierLabel: 'Repository record',
			requirement: 'at-uri',
			back: '/repositories',
		},
	},
	{
		path: '/repositories/:repo/pulls/:rkey',
		name: 'pull',
		component: domainPage,
		meta: {
			title: 'Pull request',
			section: 'Collaboration',
			description: 'Read a pull request, its status history, discussion, and patch.',
			parameter: 'repo',
			identifierLabel: 'Repository record',
			requirement: 'at-uri',
			back: '/repositories',
		},
	},
	{
		path: '/repositories/:repo/pipelines/:pipeline?',
		name: 'pipelines',
		component: domainPage,
		meta: {
			title: 'Pipelines',
			section: 'Automation',
			description: 'Browse pipeline runs and their public status history.',
			parameter: 'repo',
			identifierLabel: 'Repository record',
			requirement: 'at-uri',
			back: '/repositories',
		},
	},
	{
		path: '/repositories/:repo/artifacts/:artifact',
		name: 'artifact',
		component: domainPage,
		meta: {
			title: 'Artifact',
			section: 'Automation',
			description: 'Inspect metadata for a public pipeline artifact.',
			parameter: 'repo',
			identifierLabel: 'Repository record',
			requirement: 'at-uri',
			back: '/repositories',
		},
	},
	{
		path: '/strings/:uri',
		name: 'string',
		component: domainPage,
		meta: {
			title: 'String',
			section: 'Social',
			description: 'Read a Tangled string and its public discussion.',
			parameter: 'uri',
			identifierLabel: 'String record',
			requirement: 'at-uri',
			back: '/',
		},
	},
	{
		path: '/infrastructure',
		name: 'infrastructure',
		component: domainPage,
		meta: {
			title: 'Knots & spindles',
			section: 'Infrastructure',
			description: 'Browse the public services that host and automate Tangled work.',
		},
	},
	{
		path: '/knots/:knot',
		name: 'knot',
		component: domainPage,
		meta: {
			title: 'Knot',
			section: 'Infrastructure',
			description: 'Inspect a knot owner, version, and public keys.',
			parameter: 'knot',
			identifierLabel: 'Knot',
			requirement: 'host',
			back: '/infrastructure',
		},
	},
	{
		path: '/spindles/:spindle',
		name: 'spindle',
		component: domainPage,
		meta: {
			title: 'Spindle',
			section: 'Infrastructure',
			description: 'Inspect a public spindle, its members, and pipelines.',
			parameter: 'spindle',
			identifierLabel: 'Spindle',
			requirement: 'text',
			back: '/infrastructure',
		},
	},
	{
		path: '/labels/:scope',
		name: 'labels',
		component: domainPage,
		meta: {
			title: 'Labels',
			section: 'Infrastructure',
			description: 'Browse label definitions and operation history for a scope.',
			parameter: 'scope',
			identifierLabel: 'Scope',
			requirement: 'at-uri',
			back: '/infrastructure',
		},
	},
	{
		path: '/diagnostics/keys',
		name: 'public-keys',
		component: domainPage,
		meta: {
			title: 'Public keys',
			section: 'Diagnostics',
			description: 'Inspect public service keys without exposing management controls.',
		},
	},
	{ path: '/settings', name: 'settings', component: () => import('../views/SettingsPage.vue') },
	{ path: '/:pathMatch(.*)*', name: 'not-found', component: () => import('../views/NotFoundPage.vue') },
]

/** The application router used by web history, deep links, and Ionic transitions. */
const router = createRouter({ history: createWebHistory(import.meta.env.BASE_URL), routes })

export default router
